import { NextResponse } from "next/server";
import { getUserAndOrg } from "@/lib/org";
import { instrument, sendEmail } from "@/lib/email";

export const runtime = "nodejs";
export const maxDuration = 30;

export async function POST(request) {
  const session = await getUserAndOrg();
  if (!session?.orgId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { supabase, orgId } = session;

  const { leadId, proposalId, to, subject, body } = await request.json().catch(() => ({}));
  if (!to?.trim() || !subject?.trim() || !body?.trim()) {
    return NextResponse.json({ error: "to, subject and body are required" }, { status: 400 });
  }

  // Compliance: block suppressed / opted-out recipients.
  const { data: suppressed } = await supabase
    .from("suppressions")
    .select("email")
    .eq("org_id", orgId)
    .eq("email", to.trim())
    .maybeSingle();
  if (suppressed) {
    return NextResponse.json({ error: "This address is on your suppression list." }, { status: 409 });
  }

  // Create the email record first (tracking_id is generated by the DB).
  const { data: email, error } = await supabase
    .from("emails")
    .insert({
      org_id: orgId,
      lead_id: leadId ?? null,
      proposal_id: proposalId ?? null,
      to_email: to.trim(),
      subject: subject.trim(),
      body_html: body,
      status: "queued",
    })
    .select()
    .single();
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  const html = instrument(body, email.tracking_id, email.to_email);
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
  const unsubscribeUrl = `${appUrl}/api/unsubscribe?email=${encodeURIComponent(email.to_email)}&id=${email.tracking_id}`;

  try {
    const { id, skipped } = await sendEmail({ to: email.to_email, subject: email.subject, html, unsubscribeUrl });
    if (skipped) {
      await supabase.from("emails").update({ status: "failed", error: skipped }).eq("id", email.id);
      return NextResponse.json({ queued: false, warning: skipped, emailId: email.id });
    }
    await supabase
      .from("emails")
      .update({ status: "sent", provider_id: id, sent_at: new Date().toISOString() })
      .eq("id", email.id);
    await supabase.from("email_events").insert({ org_id: orgId, email_id: email.id, type: "sent" });
    if (leadId) {
      await supabase.from("leads").update({ status: "contacted" }).eq("id", leadId).eq("status", "new");
    }
    return NextResponse.json({ queued: true, emailId: email.id });
  } catch (e) {
    await supabase.from("emails").update({ status: "failed", error: e.message }).eq("id", email.id);
    return NextResponse.json({ error: e.message }, { status: 502 });
  }
}
