import { NextResponse } from "next/server";
import { getUserAndOrg } from "@/lib/org";
import { instrument, sendEmail, unsubscribeLink } from "@/lib/email";
import { enqueueEmail } from "@/lib/queue";
import { isRecipientAllowed, planNextSend } from "@leadforge/shared/send-planner";
import { warmupDaysLeft } from "@leadforge/shared/send-schedule";

export const runtime = "nodejs";
export const maxDuration = 30;

export async function POST(request) {
  const session = await getUserAndOrg();
  if (!session?.orgId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { supabase, orgId } = session;

  const { leadId, proposalId, to, subject, body } = await request.json().catch(() => ({}));
  if (!to?.trim() || !subject?.trim() || !body?.trim()) {
    return NextResponse.json({ error: "to, subject and body are required" }, { status: 400 });
  }

  // Compliance: block suppressed / opted-out recipients.
  const { data: suppressed } = await supabase
    .from("suppressions")
    .select("email")
    .eq("org_id", orgId)
    .eq("email", to.trim())
    .maybeSingle();
  if (suppressed) {
    return NextResponse.json({ error: "This address is on your suppression list." }, { status: 409 });
  }

  // Warm-up: only seed contacts are mailable until the domain graduates.
  const { allowed, settings } = await isRecipientAllowed(supabase, orgId, to.trim());
  if (!allowed) {
    const left = warmupDaysLeft(settings);
    return NextResponse.json(
      {
        error: `Warm-up in progress — ${left} day${left === 1 ? "" : "s"} left. Only warm-up contacts can be emailed until it finishes.`,
        warmup: true,
      },
      { status: 409 },
    );
  }

  // Pace the send: ramped daily cap, spread across the org's send window.
  const { at: sendAt, capReached, cap } = await planNextSend(supabase, orgId, { settings });
  const delay = Math.max(0, sendAt.getTime() - Date.now());

  // Create the email record first (tracking_id is generated by the DB).
  const { data: email, error } = await supabase
    .from("emails")
    .insert({
      org_id: orgId,
      lead_id: leadId ?? null,
      proposal_id: proposalId ?? null,
      to_email: to.trim(),
      subject: subject.trim(),
      body_html: body,
      status: "queued",
      kind: "outreach",
      scheduled_at: sendAt.toISOString(),
    })
    .select()
    .single();
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  // Scheduled for later → hand it to the worker and return. The worker re-checks
  // the cap and window when the job fires, so a queue that drifts self-corrects.
  if (delay > 0) {
    const queued = await enqueueEmail(email.id, orgId, delay).catch(() => false);
    if (!queued) {
      await supabase
        .from("emails")
        .update({ status: "failed", error: "scheduled send needs Redis + worker" })
        .eq("id", email.id);
      return NextResponse.json(
        { error: "Scheduled sending requires the worker (Redis) to be running." },
        { status: 503 },
      );
    }
    return NextResponse.json({ queued: true, emailId: email.id, scheduledAt: sendAt.toISOString(), capReached, cap });
  }

  // Due now → send inline so the UI can report the result immediately.
  const html = instrument(body, email.tracking_id, email.to_email);
  const unsubscribeUrl = unsubscribeLink(email.tracking_id, email.to_email);

  try {
    const { id, skipped } = await sendEmail({ to: email.to_email, subject: email.subject, html, unsubscribeUrl });
    if (skipped) {
      await supabase.from("emails").update({ status: "failed", error: skipped }).eq("id", email.id);
      return NextResponse.json({ queued: false, warning: skipped, emailId: email.id });
    }
    await supabase
      .from("emails")
      .update({ status: "sent", provider_id: id, sent_at: new Date().toISOString() })
      .eq("id", email.id);
    await supabase.from("email_events").insert({ org_id: orgId, email_id: email.id, type: "sent" });
    if (leadId) {
      await supabase.from("leads").update({ status: "contacted" }).eq("id", leadId).eq("status", "new");
    }
    return NextResponse.json({ queued: true, emailId: email.id, sent: true, cap });
  } catch (e) {
    await supabase.from("emails").update({ status: "failed", error: e.message }).eq("id", email.id);
    return NextResponse.json({ error: e.message }, { status: 502 });
  }
}
